
_main:

;DIN PT100 Marsrutizatorius.c,39 :: 		void main(){
;DIN PT100 Marsrutizatorius.c,40 :: 		TRISA = 0b00000000;
	CLRF       TRISA+0
;DIN PT100 Marsrutizatorius.c,41 :: 		TRISB = 0b00001000;
	MOVLW      8
	MOVWF      TRISB+0
;DIN PT100 Marsrutizatorius.c,43 :: 		PORTA = 0;
	CLRF       PORTA+0
;DIN PT100 Marsrutizatorius.c,44 :: 		PORTB = 0;
	CLRF       PORTB+0
;DIN PT100 Marsrutizatorius.c,45 :: 		TEMPERATURE_ROUTER_INIT();
	CALL       _TEMPERATURE_ROUTER_INIT+0
;DIN PT100 Marsrutizatorius.c,46 :: 		while(1){
L_main0:
;DIN PT100 Marsrutizatorius.c,47 :: 		TEMPERATURE_ROUTER();
	CALL       _TEMPERATURE_ROUTER+0
;DIN PT100 Marsrutizatorius.c,48 :: 		delay_ms(1);
	MOVLW      3
	MOVWF      R12+0
	MOVLW      151
	MOVWF      R13+0
L_main2:
	DECFSZ     R13+0, 1
	GOTO       L_main2
	DECFSZ     R12+0, 1
	GOTO       L_main2
	NOP
	NOP
;DIN PT100 Marsrutizatorius.c,49 :: 		}
	GOTO       L_main0
;DIN PT100 Marsrutizatorius.c,50 :: 		}
L_end_main:
	GOTO       $+0
; end of _main

_TEMPERATURE_ROUTER_INIT:

;DIN PT100 Marsrutizatorius.c,55 :: 		void TEMPERATURE_ROUTER_INIT(){
;DIN PT100 Marsrutizatorius.c,56 :: 		BEAM_SELECTION = BEAM_SELECTION_INPUT;
	MOVLW      0
	BTFSC      PORTB+0, 3
	MOVLW      1
	MOVWF      _BEAM_SELECTION+0
;DIN PT100 Marsrutizatorius.c,57 :: 		TEMPERATURE_TIMER = 0;
	CLRF       _TEMPERATURE_TIMER+0
	CLRF       _TEMPERATURE_TIMER+1
;DIN PT100 Marsrutizatorius.c,58 :: 		TEMPERATURE_POSITION = 0;
	CLRF       _TEMPERATURE_POSITION+0
;DIN PT100 Marsrutizatorius.c,59 :: 		}
L_end_TEMPERATURE_ROUTER_INIT:
	RETURN
; end of _TEMPERATURE_ROUTER_INIT

_TEMPERATURE_ROUTER:

;DIN PT100 Marsrutizatorius.c,61 :: 		void TEMPERATURE_ROUTER(){
;DIN PT100 Marsrutizatorius.c,63 :: 		if(TEMPERATURE_POSITION==0){        //OUTPUT 1
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      0
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER3
;DIN PT100 Marsrutizatorius.c,64 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 0;
	BSF        PORTB+0, 1
	BCF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,65 :: 		}
	GOTO       L_TEMPERATURE_ROUTER4
L_TEMPERATURE_ROUTER3:
;DIN PT100 Marsrutizatorius.c,66 :: 		else if(TEMPERATURE_POSITION==1){   //OUTPUT 5
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      1
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER5
;DIN PT100 Marsrutizatorius.c,67 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 1;
	BSF        PORTB+0, 1
	BCF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,68 :: 		}
	GOTO       L_TEMPERATURE_ROUTER6
L_TEMPERATURE_ROUTER5:
;DIN PT100 Marsrutizatorius.c,69 :: 		else if(TEMPERATURE_POSITION==2){   //OUTPUT 4
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      2
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER7
;DIN PT100 Marsrutizatorius.c,70 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 1;
	BCF        PORTB+0, 1
	BCF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,71 :: 		}
	GOTO       L_TEMPERATURE_ROUTER8
L_TEMPERATURE_ROUTER7:
;DIN PT100 Marsrutizatorius.c,72 :: 		else if(TEMPERATURE_POSITION==3){   //OUTPUT 6
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      3
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER9
;DIN PT100 Marsrutizatorius.c,73 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 1;
	BCF        PORTB+0, 1
	BSF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,74 :: 		}
	GOTO       L_TEMPERATURE_ROUTER10
L_TEMPERATURE_ROUTER9:
;DIN PT100 Marsrutizatorius.c,75 :: 		else if(TEMPERATURE_POSITION==4){   //OUTPUT 3
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      4
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER11
;DIN PT100 Marsrutizatorius.c,76 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 0;
	BSF        PORTB+0, 1
	BSF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,77 :: 		}
	GOTO       L_TEMPERATURE_ROUTER12
L_TEMPERATURE_ROUTER11:
;DIN PT100 Marsrutizatorius.c,78 :: 		else if(TEMPERATURE_POSITION==5){   //OUTPUT 2
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      5
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER13
;DIN PT100 Marsrutizatorius.c,79 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 0;
	BCF        PORTB+0, 1
	BSF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,80 :: 		}
	GOTO       L_TEMPERATURE_ROUTER14
L_TEMPERATURE_ROUTER13:
;DIN PT100 Marsrutizatorius.c,81 :: 		else if(TEMPERATURE_POSITION==6){   //OUTPUT 1
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      6
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER15
;DIN PT100 Marsrutizatorius.c,82 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 0;
	BSF        PORTB+0, 1
	BCF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,83 :: 		}
	GOTO       L_TEMPERATURE_ROUTER16
L_TEMPERATURE_ROUTER15:
;DIN PT100 Marsrutizatorius.c,84 :: 		else if(TEMPERATURE_POSITION==7){   //OUTPUT 5
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      7
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER17
;DIN PT100 Marsrutizatorius.c,85 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 1;
	BSF        PORTB+0, 1
	BCF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,86 :: 		}
	GOTO       L_TEMPERATURE_ROUTER18
L_TEMPERATURE_ROUTER17:
;DIN PT100 Marsrutizatorius.c,87 :: 		else if(TEMPERATURE_POSITION==8){   //OUTPUT 4
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      8
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER19
;DIN PT100 Marsrutizatorius.c,88 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 0;TEMPERATURE_CHOICE_C = 1;
	BCF        PORTB+0, 1
	BCF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,89 :: 		}
	GOTO       L_TEMPERATURE_ROUTER20
L_TEMPERATURE_ROUTER19:
;DIN PT100 Marsrutizatorius.c,90 :: 		else if(TEMPERATURE_POSITION==9){   //OUTPUT 6
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      9
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER21
;DIN PT100 Marsrutizatorius.c,91 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 1;
	BCF        PORTB+0, 1
	BSF        PORTB+0, 5
	BSF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,92 :: 		}
	GOTO       L_TEMPERATURE_ROUTER22
L_TEMPERATURE_ROUTER21:
;DIN PT100 Marsrutizatorius.c,93 :: 		else if(TEMPERATURE_POSITION==10){  //OUTPUT 3
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      10
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER23
;DIN PT100 Marsrutizatorius.c,94 :: 		TEMPERATURE_CHOICE_A = 1;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 0;
	BSF        PORTB+0, 1
	BSF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,95 :: 		}
	GOTO       L_TEMPERATURE_ROUTER24
L_TEMPERATURE_ROUTER23:
;DIN PT100 Marsrutizatorius.c,96 :: 		else if(TEMPERATURE_POSITION==11){  //OUTPUT 2
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      11
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER25
;DIN PT100 Marsrutizatorius.c,97 :: 		TEMPERATURE_CHOICE_A = 0;TEMPERATURE_CHOICE_B = 1;TEMPERATURE_CHOICE_C = 0;
	BCF        PORTB+0, 1
	BSF        PORTB+0, 5
	BCF        PORTB+0, 6
;DIN PT100 Marsrutizatorius.c,98 :: 		}
L_TEMPERATURE_ROUTER25:
L_TEMPERATURE_ROUTER24:
L_TEMPERATURE_ROUTER22:
L_TEMPERATURE_ROUTER20:
L_TEMPERATURE_ROUTER18:
L_TEMPERATURE_ROUTER16:
L_TEMPERATURE_ROUTER14:
L_TEMPERATURE_ROUTER12:
L_TEMPERATURE_ROUTER10:
L_TEMPERATURE_ROUTER8:
L_TEMPERATURE_ROUTER6:
L_TEMPERATURE_ROUTER4:
;DIN PT100 Marsrutizatorius.c,101 :: 		if(BEAM_SELECTION==0){
	MOVF       _BEAM_SELECTION+0, 0
	XORLW      0
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER26
;DIN PT100 Marsrutizatorius.c,102 :: 		if(TEMPERATURE_POSITION<6){
	MOVLW      6
	SUBWF      _TEMPERATURE_POSITION+0, 0
	BTFSC      STATUS+0, 0
	GOTO       L_TEMPERATURE_ROUTER27
;DIN PT100 Marsrutizatorius.c,103 :: 		TEMPERATURE_CHOICE_D1 = 0;
	BCF        PORTB+0, 2
;DIN PT100 Marsrutizatorius.c,104 :: 		TEMPERATURE_CHOICE_D2 = 1;
	BSF        PORTB+0, 4
;DIN PT100 Marsrutizatorius.c,105 :: 		}
	GOTO       L_TEMPERATURE_ROUTER28
L_TEMPERATURE_ROUTER27:
;DIN PT100 Marsrutizatorius.c,107 :: 		TEMPERATURE_CHOICE_D1 = 1;
	BSF        PORTB+0, 2
;DIN PT100 Marsrutizatorius.c,108 :: 		TEMPERATURE_CHOICE_D2 = 0;
	BCF        PORTB+0, 4
;DIN PT100 Marsrutizatorius.c,109 :: 		}
L_TEMPERATURE_ROUTER28:
;DIN PT100 Marsrutizatorius.c,110 :: 		}
	GOTO       L_TEMPERATURE_ROUTER29
L_TEMPERATURE_ROUTER26:
;DIN PT100 Marsrutizatorius.c,112 :: 		TEMPERATURE_CHOICE_D1 = 0;
	BCF        PORTB+0, 2
;DIN PT100 Marsrutizatorius.c,113 :: 		TEMPERATURE_CHOICE_D2 = 0;
	BCF        PORTB+0, 4
;DIN PT100 Marsrutizatorius.c,114 :: 		}
L_TEMPERATURE_ROUTER29:
;DIN PT100 Marsrutizatorius.c,118 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_MEM_START){
	MOVF       _TEMPERATURE_TIMER+1, 0
	XORLW      16
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER46
	MOVLW      104
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER46:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER30
;DIN PT100 Marsrutizatorius.c,119 :: 		OUTPUT_MEMORIZATION = 1;
	BSF        PORTA+0, 1
;DIN PT100 Marsrutizatorius.c,120 :: 		}
L_TEMPERATURE_ROUTER30:
;DIN PT100 Marsrutizatorius.c,121 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_MEM_END){
	MOVF       _TEMPERATURE_TIMER+1, 0
	XORLW      18
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER47
	MOVLW      192
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER47:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER31
;DIN PT100 Marsrutizatorius.c,122 :: 		OUTPUT_MEMORIZATION = 0;
	BCF        PORTA+0, 1
;DIN PT100 Marsrutizatorius.c,123 :: 		}
L_TEMPERATURE_ROUTER31:
;DIN PT100 Marsrutizatorius.c,126 :: 		if(TEMPERATURE_POSITION==0){
	MOVF       _TEMPERATURE_POSITION+0, 0
	XORLW      0
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER32
;DIN PT100 Marsrutizatorius.c,127 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_RESET_START){
	MOVLW      0
	XORWF      _TEMPERATURE_TIMER+1, 0
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER48
	MOVLW      0
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER48:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER33
;DIN PT100 Marsrutizatorius.c,128 :: 		OUTPUT_RESET = 1;
	BSF        PORTA+0, 0
;DIN PT100 Marsrutizatorius.c,129 :: 		}
L_TEMPERATURE_ROUTER33:
;DIN PT100 Marsrutizatorius.c,130 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_RESET_END){
	MOVF       _TEMPERATURE_TIMER+1, 0
	XORLW      2
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER49
	MOVLW      88
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER49:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER34
;DIN PT100 Marsrutizatorius.c,131 :: 		OUTPUT_RESET = 0;
	BCF        PORTA+0, 0
;DIN PT100 Marsrutizatorius.c,132 :: 		}
L_TEMPERATURE_ROUTER34:
;DIN PT100 Marsrutizatorius.c,133 :: 		}
	GOTO       L_TEMPERATURE_ROUTER35
L_TEMPERATURE_ROUTER32:
;DIN PT100 Marsrutizatorius.c,135 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_CLOCK_START){
	MOVLW      0
	XORWF      _TEMPERATURE_TIMER+1, 0
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER50
	MOVLW      0
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER50:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER36
;DIN PT100 Marsrutizatorius.c,136 :: 		OUTPUT_CLOCK = 1;
	BSF        PORTA+0, 2
;DIN PT100 Marsrutizatorius.c,137 :: 		}
L_TEMPERATURE_ROUTER36:
;DIN PT100 Marsrutizatorius.c,138 :: 		if(TEMPERATURE_TIMER==TEMPERATURE_CLOCK_END){
	MOVF       _TEMPERATURE_TIMER+1, 0
	XORLW      2
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER51
	MOVLW      88
	XORWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER51:
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER37
;DIN PT100 Marsrutizatorius.c,139 :: 		OUTPUT_CLOCK = 0;
	BCF        PORTA+0, 2
;DIN PT100 Marsrutizatorius.c,140 :: 		}
L_TEMPERATURE_ROUTER37:
;DIN PT100 Marsrutizatorius.c,141 :: 		}
L_TEMPERATURE_ROUTER35:
;DIN PT100 Marsrutizatorius.c,144 :: 		TEMPERATURE_TIMER++;
	INCF       _TEMPERATURE_TIMER+0, 1
	BTFSC      STATUS+0, 2
	INCF       _TEMPERATURE_TIMER+1, 1
;DIN PT100 Marsrutizatorius.c,145 :: 		if(TEMPERATURE_TIMER>=TEMPERATURE_CYCLE_TIME){
	MOVLW      128
	XORWF      _TEMPERATURE_TIMER+1, 0
	MOVWF      R0+0
	MOVLW      128
	XORLW      19
	SUBWF      R0+0, 0
	BTFSS      STATUS+0, 2
	GOTO       L__TEMPERATURE_ROUTER52
	MOVLW      136
	SUBWF      _TEMPERATURE_TIMER+0, 0
L__TEMPERATURE_ROUTER52:
	BTFSS      STATUS+0, 0
	GOTO       L_TEMPERATURE_ROUTER38
;DIN PT100 Marsrutizatorius.c,146 :: 		TEMPERATURE_TIMER = 0;
	CLRF       _TEMPERATURE_TIMER+0
	CLRF       _TEMPERATURE_TIMER+1
;DIN PT100 Marsrutizatorius.c,147 :: 		TEMPERATURE_POSITION++;
	INCF       _TEMPERATURE_POSITION+0, 1
;DIN PT100 Marsrutizatorius.c,148 :: 		if(BEAM_SELECTION==0){
	MOVF       _BEAM_SELECTION+0, 0
	XORLW      0
	BTFSS      STATUS+0, 2
	GOTO       L_TEMPERATURE_ROUTER39
;DIN PT100 Marsrutizatorius.c,149 :: 		if(TEMPERATURE_POSITION>12-1){
	MOVF       _TEMPERATURE_POSITION+0, 0
	SUBLW      11
	BTFSC      STATUS+0, 0
	GOTO       L_TEMPERATURE_ROUTER40
;DIN PT100 Marsrutizatorius.c,150 :: 		TEMPERATURE_POSITION = 0;
	CLRF       _TEMPERATURE_POSITION+0
;DIN PT100 Marsrutizatorius.c,151 :: 		}
L_TEMPERATURE_ROUTER40:
;DIN PT100 Marsrutizatorius.c,152 :: 		}
	GOTO       L_TEMPERATURE_ROUTER41
L_TEMPERATURE_ROUTER39:
;DIN PT100 Marsrutizatorius.c,154 :: 		if(TEMPERATURE_POSITION>6-1){
	MOVF       _TEMPERATURE_POSITION+0, 0
	SUBLW      5
	BTFSC      STATUS+0, 0
	GOTO       L_TEMPERATURE_ROUTER42
;DIN PT100 Marsrutizatorius.c,155 :: 		TEMPERATURE_POSITION = 0;
	CLRF       _TEMPERATURE_POSITION+0
;DIN PT100 Marsrutizatorius.c,156 :: 		}
L_TEMPERATURE_ROUTER42:
;DIN PT100 Marsrutizatorius.c,157 :: 		}
L_TEMPERATURE_ROUTER41:
;DIN PT100 Marsrutizatorius.c,158 :: 		}
L_TEMPERATURE_ROUTER38:
;DIN PT100 Marsrutizatorius.c,161 :: 		}
L_end_TEMPERATURE_ROUTER:
	RETURN
; end of _TEMPERATURE_ROUTER
